# Generated by Django 5.0.3 on 2024-03-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id_md', models.AutoField(primary_key=True, serialize=False)),
                ('title_md', models.CharField(max_length=50)),
                ('definition_md', models.TextField()),
                ('vocabulary_md', models.BooleanField(default=False)),
                ('pragmatic_programmer_md', models.BooleanField(default=False)),
                ('created_date_md', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
