# Generated by Django 5.0.2 on 2024-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='tags',
            field=models.ManyToManyField(to='fields.tag'),
        ),
    ]
