# Generated by Django 5.0.3 on 2024-04-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_field_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='created_date_md',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='definition_md',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='id_md',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='title_md',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='field',
            name='pragmatic_programmer_md',
        ),
        migrations.RemoveField(
            model_name='field',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='field',
            name='vocabulary_md',
        ),
    ]
