# Generated by Django 5.0.3 on 2024-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_rename_created_date_md_field_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='fk_id',
            field=models.ManyToManyField(blank=True, to='fields.tag'),
        ),
    ]
