# Generated by Django 5.0.3 on 2024-04-24 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0005_field_fk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='fk_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fields.field'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
