# Generated by Django 5.0.2 on 2024-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0006_remove_field_fk_id_remove_tag_name_tag_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='field',
        ),
        migrations.AddField(
            model_name='field',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='fields.tag'),
        ),
    ]
